<?xml version="1.0" encoding="UTF-8"?> 
<!-- XML 엘리먼트 작성 규칙 정의하기
=> 자식 엘리먼트의 개수 지정하기
   기본: 필수 1개
   ?: 선택 1개
   *: 0개 이상
   +: 1개 이상
  -->
<!DOCTYPE books [
  <!ELEMENT books (book)+>
  <!ELEMENT book (title,content?,press,price,author*)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT content (#PCDATA)>
  <!ELEMENT press (#PCDATA)>
  <!ELEMENT price (#PCDATA)>
  <!ELEMENT author (#PCDATA)>
]>
<books>
  <book> 
    <title>자바 프로그래밍</title>
    <content>자바 기초 문법에 대한 책이다</content>
    <press>비트출판사</press>
    <price>32000</price>
  </book>
  <book> 
    <title>자바 프로그래밍2</title>
    <press>비트출판사</press>
    <price>32000</price>
    <author>홍길동</author>
    <author>임꺽정</author>
  </book>
</books>
